// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace taskmanager.events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class TaskCreatedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""TaskCreatedEvent"",""namespace"":""taskmanager.events"",""fields"":[{""name"":""taskId"",""type"":""string""},{""name"":""userId"",""type"":""string""},{""name"":""title"",""type"":""string""},{""name"":""description"",""default"":null,""type"":[""null"",""string""]},{""name"":""isCompleted"",""type"":""boolean""},{""name"":""occuredAt"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""priority"",""default"":null,""type"":[""null"",""int""]}]}");
		private string _taskId;
		private string _userId;
		private string _title;
		private string _description;
		private bool _isCompleted;
		private System.DateTime _occuredAt;
		private System.Nullable<System.Int32> _priority;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return TaskCreatedEvent._SCHEMA;
			}
		}
		public string taskId
		{
			get
			{
				return this._taskId;
			}
			set
			{
				this._taskId = value;
			}
		}
		public string userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				this._userId = value;
			}
		}
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		public bool isCompleted
		{
			get
			{
				return this._isCompleted;
			}
			set
			{
				this._isCompleted = value;
			}
		}
		public System.DateTime occuredAt
		{
			get
			{
				return this._occuredAt;
			}
			set
			{
				this._occuredAt = value;
			}
		}
		public System.Nullable<System.Int32> priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				this._priority = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.taskId;
			case 1: return this.userId;
			case 2: return this.title;
			case 3: return this.description;
			case 4: return this.isCompleted;
			case 5: return this.occuredAt;
			case 6: return this.priority;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.taskId = (System.String)fieldValue; break;
			case 1: this.userId = (System.String)fieldValue; break;
			case 2: this.title = (System.String)fieldValue; break;
			case 3: this.description = (System.String)fieldValue; break;
			case 4: this.isCompleted = (System.Boolean)fieldValue; break;
			case 5: this.occuredAt = (System.DateTime)fieldValue; break;
			case 6: this.priority = (System.Nullable<System.Int32>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
